version: '3.1'

services:

  server:
    container_name: music-player
    build: .
    restart: always
    ports:
      - 5555:5555
    environment:
      - DATABASE_URL=sqlite:/db/database.sqlite
    volumes:
      - ./data:/db
      - /data/media/music:/data/media/music

