version: '3.1'

services:

  site:
    container_name: music.akisel.ru
    build: .
    restart: always
    ports:
      - 5555:5555
    environment:
      - DATABASE=/db/database.sqlite
    volumes:
      - ./data:/db
      - /data/media/music:/data/media/music

